# Generated by Django 2.2.7 on 2019-12-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('light_gallery_video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightgalleryvideo',
            name='muted',
            field=models.BooleanField(default=False, verbose_name='Muted'),
        ),
    ]
