# Generated by Django 2.2.7 on 2020-02-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('light_gallery_video', '0003_video_muted'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightgalleryvideo',
            name='bootstrap4_column_class',
            field=models.CharField(blank=True, default='col-lg-4', max_length=255, verbose_name='Bootstrap4 column class'),
        ),
        migrations.AddField(
            model_name='lightgalleryvideo',
            name='bootstrap4_row_class',
            field=models.CharField(blank=True, default='row', max_length=255, verbose_name='Bootstrap4 row class'),
        ),
    ]
