# Generated by Django 2.2.7 on 2020-02-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('light_gallery_video', '0004_auto_20200222_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightgalleryvideo',
            name='bootstrap4_image_class',
            field=models.CharField(blank=True, default='py-1', max_length=255, verbose_name='Bootstrap4 image class'),
        ),
        migrations.AlterField(
            model_name='lightgalleryvideo',
            name='bootstrap4_column_class',
            field=models.CharField(blank=True, default='col-lg-3', max_length=255, verbose_name='Bootstrap4 column class'),
        ),
    ]
