# Generated by Django 2.2.7 on 2020-02-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('light_gallery_video', '0005_auto_20200222_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightgalleryvideo',
            name='bootstrap4_column_class',
            field=models.CharField(blank=True, default='col-lg-3', max_length=255, verbose_name='Bootstrap4 column class'),
        ),
    ]
